#!/usr/bin/env bash
#run nginx as another user
set -x
pkill apache2
sed -i.bak '2s/^/user nginx;\n/' /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
sudo chmod u+r /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
