#!/usr/bin/env bash
#run nginx as another user
pkill apache2
sed -i 's/\([ :]\)80 default/\18080 default/' /etc/nginx/sites-enabled/default
find /etc/nginx/nginx.conf | tee >(xargs chmod u+r) | sudo xargs chown nginx
sudo -u nginx service nginx start
