#!/usr/bin/env bash
# Tranfer a file uses scp command protocol rom user arguments

if [ $# == 4 ]; then
	scp -i "$4" "$1" "$3@$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi
